---
language: python
python: "2.7"

env:
  - SITE=test.yml

install:
  - "pip install --upgrade pip"
  - "pip install ansible"
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  - "ansible-playbook -i tests/inventory tests/$SITE --syntax-check"
  - "ansible-playbook -i tests/inventory tests/$SITE --connection=local --sudo"
